import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ArrowLeft, User, Phone, Mail, MapPin, Package, ExternalLink, TrendingUp, Activity } from 'lucide-react';
import { useChatStore } from '@/store/chatStore';
function formatCurrency(amount) {
    return `₡${amount.toLocaleString()}`;
}
function formatDate(date) {
    return date.toLocaleDateString('es-ES', { month: 'short', year: 'numeric' });
}
export function CustomerInfo() {
    const conversation = useChatStore(state => state.getSelectedConversation());
    const setView = useChatStore(state => state.setView);
    const toggleInfoPanel = useChatStore(state => state.toggleInfoPanel);
    if (!conversation) {
        return (_jsx("aside", { className: "w-full h-full bg-[#111111] border-l border-white/10 flex items-center justify-center", children: _jsx("p", { className: "text-white/40 text-sm", children: "Selecciona una conversaci\u00F3n" }) }));
    }
    const { customer } = conversation;
    return (_jsxs("aside", { className: "w-full h-full bg-[#111111] border-l border-white/10 flex flex-col", children: [_jsxs("div", { className: "h-16 flex items-center justify-between px-4 border-b border-white/10", children: [_jsx("button", { onClick: () => setView('chat'), className: "lg:hidden p-2 hover:bg-white/10 rounded-lg transition-colors", children: _jsx(ArrowLeft, { className: "w-5 h-5 text-white/70" }) }), _jsx("h2", { className: "text-white font-medium", children: "Informaci\u00F3n del Cliente" }), _jsx("button", { onClick: toggleInfoPanel, className: "hidden lg:block p-2 hover:bg-white/10 rounded-lg transition-colors", children: _jsx("span", { className: "text-white/50 text-lg", children: "\u00D7" }) })] }), _jsxs("div", { className: "flex-1 overflow-y-auto p-4", children: [_jsxs("div", { className: "text-center mb-6", children: [_jsx("div", { className: "w-20 h-20 bg-gradient-to-br from-[#3B82F6] to-[#00FF88] rounded-full flex items-center justify-center mx-auto mb-3", children: _jsx(User, { className: "w-10 h-10 text-white" }) }), _jsx("h3", { className: "text-white font-semibold text-lg", children: customer.name }), _jsxs("p", { className: "text-white/50 text-sm", children: ["Cliente desde ", formatDate(customer.customerSince)] })] }), _jsxs("div", { className: "space-y-3 mb-6", children: [_jsxs("div", { className: "flex items-center gap-3 text-sm", children: [_jsx(Phone, { className: "w-4 h-4 text-white/40" }), _jsx("span", { className: "text-white/70", children: customer.phone })] }), customer.email && (_jsxs("div", { className: "flex items-center gap-3 text-sm", children: [_jsx(Mail, { className: "w-4 h-4 text-white/40" }), _jsx("span", { className: "text-white/70", children: customer.email })] })), customer.address && (_jsxs("div", { className: "flex items-center gap-3 text-sm", children: [_jsx(MapPin, { className: "w-4 h-4 text-white/40" }), _jsx("span", { className: "text-white/70", children: customer.address })] }))] }), customer.activeOrders.length > 0 && (_jsxs("div", { className: "mb-6", children: [_jsxs("h4", { className: "text-white/50 text-xs uppercase tracking-wider mb-3 flex items-center gap-2", children: [_jsx(Package, { className: "w-3.5 h-3.5" }), "Pedidos Activos"] }), _jsx("div", { className: "space-y-2", children: customer.activeOrders.map((order) => (_jsxs("div", { className: "bg-white/5 rounded-lg p-3 border border-white/10", children: [_jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsx("span", { className: "text-white font-medium text-sm", children: order.id }), _jsx("span", { className: `text-xs px-2 py-0.5 rounded-full ${order.status === 'ready'
                                                        ? 'bg-[#00FF88]/20 text-[#00FF88]'
                                                        : 'bg-[#3B82F6]/20 text-[#3B82F6]'}`, children: order.status === 'ready' ? '✅ Listo' : '🔄 En Proceso' })] }), _jsx("p", { className: "text-white/60 text-xs", children: order.items.map(item => `${item.product.name} (${item.size})`).join(', ') }), _jsx("p", { className: "text-white font-medium text-sm mt-2", children: formatCurrency(order.total) })] }, order.id))) })] })), _jsxs("div", { className: "mb-6", children: [_jsxs("h4", { className: "text-white/50 text-xs uppercase tracking-wider mb-3 flex items-center gap-2", children: [_jsx(TrendingUp, { className: "w-3.5 h-3.5" }), "Historial"] }), _jsxs("div", { className: "grid grid-cols-2 gap-3", children: [_jsxs("div", { className: "bg-white/5 rounded-lg p-3", children: [_jsx("p", { className: "text-white/50 text-xs", children: "Total pedidos" }), _jsx("p", { className: "text-white font-semibold text-lg", children: customer.totalOrders })] }), _jsxs("div", { className: "bg-white/5 rounded-lg p-3", children: [_jsx("p", { className: "text-white/50 text-xs", children: "Total compras" }), _jsx("p", { className: "text-white font-semibold text-lg", children: formatCurrency(customer.totalSpent) })] })] }), customer.lastOrderDate && (_jsxs("p", { className: "text-white/50 text-xs mt-2", children: ["\u00DAltimo pedido: ", formatDate(customer.lastOrderDate)] }))] }), customer.sports.length > 0 && (_jsxs("div", { className: "mb-6", children: [_jsxs("h4", { className: "text-white/50 text-xs uppercase tracking-wider mb-3 flex items-center gap-2", children: [_jsx(Activity, { className: "w-3.5 h-3.5" }), "Deportes"] }), _jsx("div", { className: "flex flex-wrap gap-2", children: customer.sports.map((sport, idx) => (_jsx("span", { className: "px-3 py-1 bg-white/10 rounded-full text-xs text-white/70", children: sport }, idx))) })] })), customer.frequentProducts.length > 0 && (_jsxs("div", { className: "mb-6", children: [_jsx("h4", { className: "text-white/50 text-xs uppercase tracking-wider mb-3", children: "Productos Frecuentes" }), _jsx("div", { className: "space-y-2", children: customer.frequentProducts.map((product, idx) => (_jsxs("div", { className: "flex items-center justify-between py-2 border-b border-white/5 last:border-0", children: [_jsxs("span", { className: "text-white/70 text-sm", children: [product.emoji, " ", product.name] }), _jsxs("span", { className: "text-white/50 text-xs", children: [product.count, " compras"] })] }, idx))) })] })), _jsxs("div", { className: "space-y-2", children: [_jsx("button", { className: "w-full py-2.5 bg-white/5 hover:bg-white/10 text-white/70 text-sm rounded-lg transition-colors flex items-center justify-center gap-2", children: "Ver perfil completo" }), _jsxs("button", { className: "w-full py-2.5 bg-white/5 hover:bg-white/10 text-white/70 text-sm rounded-lg transition-colors flex items-center justify-center gap-2", children: ["Ver en Shopify", _jsx(ExternalLink, { className: "w-4 h-4" })] })] })] })] }));
}
